#!/usr/bin/env python3
"""Render flow track overlays on MP4 videos from DROID episodes.

This script takes tracks.npz files (generated by generate_tracks_and_metadata.py)
and overlays the 3D contact tracks onto the original MP4 videos.

Since tracks.npz may not contain camera intrinsics, we estimate them from video dimensions.
"""

import argparse
import os
import sys
import glob
from pathlib import Path

import cv2
import numpy as np

# Default ZED camera parameters (approximate for 1280x720)
DEFAULT_FX_SCALE = 0.42  # fx = 0.42 * width ≈ 537 for 1280px


def estimate_intrinsics(width: int, height: int) -> np.ndarray:
    """Estimate camera intrinsics from video dimensions."""
    fx = DEFAULT_FX_SCALE * width
    fy = fx
    cx = width / 2.0
    cy = height / 2.0
    return np.array([[fx, 0, cx], [0, fy, cy], [0, 0, 1]], dtype=np.float64)


def project_points(points_3d: np.ndarray, K: np.ndarray, world_T_cam: np.ndarray,
                   width: int, height: int, min_depth: float = 0.01):
    """Project 3D points to 2D image coordinates."""
    if points_3d is None or len(points_3d) == 0:
        return None
    
    # Transform to camera frame
    cam_T_world = np.linalg.inv(world_T_cam)
    R = cam_T_world[:3, :3]
    t = cam_T_world[:3, 3]
    
    points_cam = (R @ points_3d.T).T + t
    
    # Filter by depth
    valid_mask = points_cam[:, 2] > min_depth
    
    # Project to image
    uv = np.zeros((len(points_3d), 2))
    uv[:] = np.nan
    
    if np.any(valid_mask):
        valid_pts = points_cam[valid_mask]
        z = valid_pts[:, 2]
        x = valid_pts[:, 0] / z
        y = valid_pts[:, 1] / z
        
        u = K[0, 0] * x + K[0, 2]
        v = K[1, 1] * y + K[1, 2]
        
        # Check bounds
        in_bounds = (u >= 0) & (u < width) & (v >= 0) & (v < height)
        
        valid_indices = np.where(valid_mask)[0]
        for i, idx in enumerate(valid_indices):
            if in_bounds[i]:
                uv[idx, 0] = u[i]
                uv[idx, 1] = v[i]
    
    return uv


def draw_points(image: np.ndarray, uv: np.ndarray, colors: np.ndarray = None,
                radius: int = 4):
    """Draw projected points on image."""
    if uv is None:
        return image
    
    for i, pt in enumerate(uv):
        if np.isnan(pt[0]) or np.isnan(pt[1]):
            continue
        
        x, y = int(pt[0]), int(pt[1])
        color = tuple(int(c) for c in colors[i]) if colors is not None else (0, 255, 255)
        cv2.circle(image, (x, y), radius, color, -1)
    
    return image


def draw_trails(image: np.ndarray, tracks_window: np.ndarray, K: np.ndarray,
                world_T_cam: np.ndarray, width: int, height: int,
                colors: np.ndarray = None, alpha: float = 0.3):
    """Draw track trails connecting consecutive frames."""
    if tracks_window is None or len(tracks_window) < 2:
        return image
    
    overlay = image.copy()
    num_pts = tracks_window.shape[1]
    
    for t in range(len(tracks_window) - 1):
        uv1 = project_points(tracks_window[t], K, world_T_cam, width, height)
        uv2 = project_points(tracks_window[t + 1], K, world_T_cam, width, height)
        
        if uv1 is None or uv2 is None:
            continue
        
        for i in range(num_pts):
            if np.isnan(uv1[i, 0]) or np.isnan(uv2[i, 0]):
                continue
            
            pt1 = (int(uv1[i, 0]), int(uv1[i, 1]))
            pt2 = (int(uv2[i, 0]), int(uv2[i, 1]))
            color = tuple(int(c) for c in colors[i]) if colors is not None else (255, 255, 0)
            cv2.line(overlay, pt1, pt2, color, 1)
    
    cv2.addWeighted(overlay, alpha, image, 1 - alpha, 0, image)
    return image


def draw_centroid_trajectory(image: np.ndarray, centroids: np.ndarray, 
                             current_idx: int, K: np.ndarray, 
                             world_T_cam: np.ndarray, width: int, height: int,
                             color: tuple = (0, 255, 255), trail_length: int = 50):
    """Draw centroid trajectory as a colored line."""
    if centroids is None or len(centroids) < 2:
        return image
    
    start_idx = max(0, current_idx - trail_length)
    trajectory = centroids[start_idx:current_idx + 1]
    
    uv = project_points(trajectory, K, world_T_cam, width, height)
    if uv is None:
        return image
    
    for i in range(len(uv) - 1):
        if np.isnan(uv[i, 0]) or np.isnan(uv[i + 1, 0]):
            continue
        pt1 = (int(uv[i, 0]), int(uv[i, 1]))
        pt2 = (int(uv[i + 1, 0]), int(uv[i + 1, 1]))
        cv2.line(image, pt1, pt2, color, 2)
    
    # Draw current position as larger circle
    if current_idx < len(uv) and not np.isnan(uv[-1, 0]):
        center = (int(uv[-1, 0]), int(uv[-1, 1]))
        cv2.circle(image, center, 8, color, -1)
        cv2.circle(image, center, 8, (0, 0, 0), 2)
    
    return image


def render_episode_videos(
    tracks_path: str,
    video_dir: str,
    output_dir: str,
    max_frames: int = None,
    trail_length: int = 10,
):
    """Render flow overlay videos for an episode."""
    
    # Load tracks
    tracks = np.load(tracks_path, allow_pickle=True)
    tracks_3d = tracks.get('tracks_3d')
    contact_centroids = tracks.get('contact_centroids')
    normalized_centroids = tracks.get('normalized_centroids')
    frame_to_normalized_idx = tracks.get('frame_to_normalized_idx')
    
    if tracks_3d is None:
        print(f"  [ERROR] No tracks_3d in {tracks_path}")
        return []
    
    num_frames = tracks_3d.shape[0]
    num_points = tracks_3d.shape[1]
    num_contact_pts = num_points // 2
    
    print(f"  Tracks: {num_frames} frames, {num_points} points")
    
    # Track colors (blue for left finger, green for right)
    track_colors = np.zeros((num_points, 3), dtype=np.uint8)
    track_colors[:num_contact_pts, :] = [255, 127, 51]  # BGR Blue-ish
    track_colors[num_contact_pts:, :] = [127, 255, 51]  # BGR Green-ish
    
    # Find MP4 videos
    mp4_files = glob.glob(os.path.join(video_dir, "*.mp4"))
    mp4_files = [f for f in mp4_files if '-stereo' not in f]  # Skip stereo versions
    
    if not mp4_files:
        print(f"  [ERROR] No MP4 files found in {video_dir}")
        return []
    
    print(f"  Found {len(mp4_files)} cameras")
    
    os.makedirs(output_dir, exist_ok=True)
    output_files = []
    
    # Try to find extrinsics from trajectory.h5
    episode_dir = os.path.dirname(os.path.dirname(video_dir))  # Go up from recordings/MP4
    h5_path = os.path.join(episode_dir, "trajectory.h5")
    
    extrinsics_dict = {}
    wrist_serial = None
    
    if os.path.exists(h5_path):
        try:
            import h5py
            with h5py.File(h5_path, 'r') as h5:
                cam_extr = h5['observation/camera_extrinsics']
                cam_type = h5['observation/camera_type']
                
                for key in cam_extr.keys():
                    if '_left' in key and 'gripper_offset' not in key:
                        serial = key.replace('_left', '')
                        extr_data = cam_extr[key][:]  # [T, 6] - position + euler angles
                        
                        # Check if wrist camera (0 = wrist, 1 = external)
                        if serial in cam_type:
                            cam_type_arr = cam_type[serial][:]
                            # Use first frame's type
                            if cam_type_arr[0] == 0:
                                wrist_serial = serial
                        
                        extrinsics_dict[serial] = extr_data
                
                print(f"  Loaded extrinsics for {len(extrinsics_dict)} cameras from trajectory.h5")
                if wrist_serial:
                    print(f"  Wrist camera: {wrist_serial}")
        except Exception as e:
            import traceback
            print(f"  [WARN] Could not load extrinsics: {e}")
            traceback.print_exc()
    
    # Process each camera
    for mp4_path in mp4_files:
        filename = os.path.basename(mp4_path)
        serial = filename.replace('.mp4', '')
        
        print(f"  Processing camera {serial}...")
        
        cap = cv2.VideoCapture(mp4_path)
        if not cap.isOpened():
            print(f"    [ERROR] Cannot open {mp4_path}")
            continue
        
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
        video_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        
        K = estimate_intrinsics(width, height)
        
        # Get extrinsics
        is_wrist = (serial == wrist_serial)
        
        if serial in extrinsics_dict:
            extr_data = extrinsics_dict[serial]
            # Convert [pos, euler] to 4x4 transform
            # For now, use a simple approximation assuming external cameras are static
            if not is_wrist:
                # External camera - use first frame pose as static
                pos = extr_data[0, :3]
                euler = extr_data[0, 3:6]
                # Simple rotation matrix from euler angles (ZYX convention)
                from scipy.spatial.transform import Rotation
                R = Rotation.from_euler('ZYX', euler).as_matrix()
                world_T_cam = np.eye(4)
                world_T_cam[:3, :3] = R
                world_T_cam[:3, 3] = pos
            else:
                # Wrist camera - per-frame transform
                wrist_transforms = []
                from scipy.spatial.transform import Rotation
                for i in range(len(extr_data)):
                    pos = extr_data[i, :3]
                    euler = extr_data[i, 3:6]
                    R = Rotation.from_euler('ZYX', euler).as_matrix()
                    T = np.eye(4)
                    T[:3, :3] = R
                    T[:3, 3] = pos
                    wrist_transforms.append(T)
                wrist_transforms = np.array(wrist_transforms)
        else:
            # Use identity transform if no extrinsics available
            print(f"    [WARN] No extrinsics for {serial}, using identity")
            world_T_cam = np.eye(4)
            is_wrist = False
        
        actual_frames = min(num_frames, video_frames)
        if max_frames:
            actual_frames = min(actual_frames, max_frames)
        
        # Create output video
        output_path = os.path.join(output_dir, f"{serial}_flow.mp4")
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        writer = cv2.VideoWriter(output_path, fourcc, fps, (width, height))
        
        for frame_idx in range(actual_frames):
            ret, frame = cap.read()
            if not ret:
                break
            
            # Get camera pose for this frame
            if is_wrist and 'wrist_transforms' in dir():
                if frame_idx < len(wrist_transforms):
                    world_T_cam = wrist_transforms[frame_idx]
                else:
                    continue
            
            # Project and draw track points
            track_pts = tracks_3d[frame_idx]
            uv = project_points(track_pts, K, world_T_cam, width, height)
            frame = draw_points(frame, uv, track_colors, radius=4)
            
            # Draw track trails
            if trail_length > 1:
                start_idx = max(0, frame_idx - trail_length + 1)
                tracks_window = tracks_3d[start_idx:frame_idx + 1]
                frame = draw_trails(frame, tracks_window, K, world_T_cam, 
                                   width, height, track_colors, alpha=0.5)
            
            # Draw centroid trajectory
            frame = draw_centroid_trajectory(
                frame, contact_centroids, frame_idx, K, world_T_cam,
                width, height, color=(0, 255, 255), trail_length=30
            )
            
            # Add frame info overlay
            if normalized_centroids is not None and frame_to_normalized_idx is not None:
                norm_idx = int(frame_to_normalized_idx[frame_idx])
                text = f"Frame {frame_idx}/{actual_frames-1} | Norm: {norm_idx}/{len(normalized_centroids)-1}"
            else:
                text = f"Frame {frame_idx}/{actual_frames-1}"
            
            cv2.putText(frame, text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
            cv2.putText(frame, text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 0), 1)
            
            writer.write(frame)
            
            if frame_idx % 30 == 0:
                print(f"    Frame {frame_idx}/{actual_frames}")
        
        cap.release()
        writer.release()
        print(f"    Saved: {output_path}")
        output_files.append(output_path)
    
    return output_files


def find_episodes_with_videos(test_data_dir: str, droid_raw_dir: str):
    """Find episodes that have both tracks.npz and matching video files."""
    episodes = []
    
    for tracks_path in glob.glob(os.path.join(test_data_dir, "**", "tracks.npz"), recursive=True):
        # Get relative path from test_data_dir
        rel_path = os.path.relpath(os.path.dirname(tracks_path), test_data_dir)
        
        # Check for corresponding video directory in droid_raw
        video_dir = os.path.join(droid_raw_dir, rel_path, "recordings", "MP4")
        
        if os.path.exists(video_dir):
            mp4_files = glob.glob(os.path.join(video_dir, "*.mp4"))
            mp4_files = [f for f in mp4_files if '-stereo' not in f]
            if mp4_files:
                episodes.append({
                    'tracks_path': tracks_path,
                    'video_dir': video_dir,
                    'episode_name': os.path.basename(os.path.dirname(tracks_path)),
                })
    
    return episodes


def main():
    parser = argparse.ArgumentParser(description="Render flow overlay videos from tracks.npz")
    parser.add_argument("--tracks_dir", default="/workspace/test_data",
                        help="Directory containing tracks.npz files")
    parser.add_argument("--droid_raw", default="/data/droid/data/droid_raw/1.0.1",
                        help="DROID raw data directory with MP4 videos")
    parser.add_argument("--output_dir", default="/workspace/output_videos",
                        help="Output directory for rendered videos")
    parser.add_argument("--max_episodes", type=int, default=None,
                        help="Maximum number of episodes to process")
    parser.add_argument("--max_frames", type=int, default=None,
                        help="Maximum frames per video")
    parser.add_argument("--trail_length", type=int, default=10,
                        help="Track trail length in frames")
    
    args = parser.parse_args()
    
    print("=" * 60)
    print("Flow Video Renderer")
    print("=" * 60)
    
    # Find episodes
    episodes = find_episodes_with_videos(args.tracks_dir, args.droid_raw)
    
    if not episodes:
        print("[ERROR] No episodes found with both tracks.npz and video files")
        return 1
    
    print(f"\nFound {len(episodes)} episodes with tracks and videos")
    
    if args.max_episodes:
        episodes = episodes[:args.max_episodes]
        print(f"Processing first {len(episodes)} episodes")
    
    os.makedirs(args.output_dir, exist_ok=True)
    
    all_outputs = []
    
    for i, ep in enumerate(episodes, 1):
        print(f"\n[{i}/{len(episodes)}] {ep['episode_name']}")
        print(f"  Tracks: {ep['tracks_path']}")
        print(f"  Videos: {ep['video_dir']}")
        
        ep_output_dir = os.path.join(args.output_dir, ep['episode_name'])
        
        outputs = render_episode_videos(
            ep['tracks_path'],
            ep['video_dir'],
            ep_output_dir,
            max_frames=args.max_frames,
            trail_length=args.trail_length,
        )
        
        all_outputs.extend(outputs)
    
    print("\n" + "=" * 60)
    print(f"[DONE] Rendered {len(all_outputs)} videos")
    print(f"Output directory: {args.output_dir}")
    print("=" * 60)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
